### ISSUE TITLE
Credential Seeding data fix

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#108]
**Summary**
Update the seeding data file for the credential by setting the expiry date for all (except Traceability v2) to 16th of Oct. 2024.
Traceability v2 should get set to 30.06.2025.

--

~~Additionally (for test reasons) an expired credential as well as a future credential needs to get shown. Please configure the following test credentials (should be highlighted as test data)~~

~~- Traceability v0 (valid from: 01.01.2023; expiry: 31.12.2023)~~
~~- FrameWorkAgreement (valid from: 16.10.2024; expiry: 16.10.2025) - not useCase specific~~

**Comment by Phil91** [comment]
I'd like to split this into two issues. one with the expiry adjustments, one with the test credentials. The test credentials will need a bit more work I guess, the expiry adjustments are already done within PR #115

**Comment by jjeroch** [comment]
Ok, separation via ticket: https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/118
