### ISSUE TITLE
Enable filter and adjust backend logic of the endpoint `GET /api/issuer/certificates

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#111]
**Description:**
Currently, the endpoint `GET /api/issuer` responds with all credentials. However, we need to enhance the endpoint to enable the user to only include credentials that require a separate approval.

Filter: Manuel vs Automatic

Manuel: Credential is only created if a manual approval is given
Automatic: No separate approval needed, credential created as part of configured/implemented workflows

**Changes:**
1. Enable a filter to identify credentials that need a separate approval.
2. Adjust the backend logic of the endpoint to only respond with credentials that require a separate approval.

**Expected Outcome:**
After implementing these changes, the endpoint `GET /api/issuer` will (depending on the used filter value) only return credentials that need a separate approval, ensuring better control and security in the credential issuance process.

Note if no filter value is provided, all credential are responded (as currently implemented)

**Comment by Phil91** [comment]
@jjeroch the /certificates endpoint currently only returns membership and bpn credentials thus the returned values are all automatically approved. and we never will have a result for manual approval ones. I think the adjustment is only making sense if we combine the /certificates and /useCaseParticipation endpoint.
