### ISSUE TITLE
Remove hard error handling for conflicting resource

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#112]
**Description:**
The current response of the API is returning a hard error for conflicting resources. This hard error is causing unnecessary restrictions and hindering the smooth functioning of the system. 

**API Response:**
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.8",
    "title": "The resource is in conflict with the current request.",
    "status": 409,
    "errors": {
        "Org.Eclipse.TractusX.SsiCredentialIssuer.Service": [
            "There should only be one pending or active ssi detail be assigned"
        ]
    },
    "errorId": "368d63b3-0d12-4d36-9458-ce8d1ba10e2a",
    "details": [
        {
            "errorCode": "MULTIPLE_SSI_DETAIL",
            "type": "IssuerErrors",
            "message": "There should only be one pending or active ssi detail be assigned",
            "parameters": []
        }
    ]
}
```

**Expected Behavior:**
The hard validation for conflicting resources should be removed to allow for more flexibility in handling such scenarios. Instead of returning a hard error, a more informative and user-friendly error message should be provided, allowing the user to understand the issue and take appropriate actions.

**Comment by jjeroch** [comment]
Example on INT: bpnl00000007

**Comment by Phil91** [comment]
> Example on INT: bpnl00000007

Is this the correct bpn? there seems to be something missing at the end
