### ISSUE TITLE
(Dev/INT) Prepare to run BPN:DID Resolver Component

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#12]
### Scope
Participant gets enabled to resolve a participant BPN to a did
Possible Reference solution: https://github.com/Metaform/bdrs/tree/main
https://github.com/eclipse-tractusx/bpn-did-resolution-service

###Architecture

<img width="713" alt="image" src="https://github.com/eclipse-tractusx/ssi-credential-issuer/assets/94133633/cf89b666-5a89-4a93-90c2-8179da92099e">

### Authentication
Thinking about enabling access via SSI VCs (e.g. all companies with a membership credential can access the service)
The VC is ideally put into the header

### Request Details

GET via BPN the did (via the did-regsitry)

```
{
"content": {
   ["{BPNL}","{did}"],
   ["{BPNL}","{did}"],
   ["{BPNL}","{did}"]
 }
}
```

- only response those where did is existing
- if we have duplicates; we provide 

### Non-Tech
- Highly available
- All connectors (no matter where they are located) would need to call the service (...note: we are thinking about a connector cache strategy)

### Details
After running the refinement; we aligned that the reference solution https://github.com/eclipse-tractusx/bpn-did-resolution-service will be taken over by us.
We will run the service inside our internal env.; the team around the reference solution development will support on functional development as well as bug fixing.

Ticket stays in place for Helm Chart review; environment config file creation; etc....

**Comment by jjeroch** [comment]
Open discussion: authentication with SSI or OIDC

**Comment by evegufy** [comment]
consortia specific config is kept in the following branch: https://github.com/eclipse-tractusx/bpn-did-resolution-service/tree/chore/consortia-env

**Comment by evegufy** [comment]
BDRS runs now stable on int (and dev) with the 0.0.4 version
https://github.com/eclipse-tractusx/bpn-did-resolution-service/tree/chore/0.0.3-consortia-envs

**Comment by jjeroch** [comment]
setting ticket to "user ready" tests are successfully started
