### ISSUE TITLE
Spelling Mistake "BusinessPartnerCredential"

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#130]
Please check once the BusinessPartnerCredential.
It seems that the issuer component has a spelling mistake and creates the credential as `BusinesspartnerCredential` instead of `BusinessPartnerCredential`

If the assumption is right, following updates are needed

- fix the spelling mistake as part of the code
- as soon as the INT deployment took place, manually adjust/fix the credentials created with the wrong spelling

**Comment by Phil91** [comment]
@jjeroch could you please provide some further information? I did check the issuer wallet and didn't see any BusinessPartner Credentials with a spelling mistake.

**Comment by jjeroch** [comment]
issue npt reproducable
