### ISSUE TITLE
missing reference your Contribution guideline in general ReadMe

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/ssi-credential-issuer#133]
Reference your Contribution guideline in the general Readme.md file

Maybe you could reference https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/ssi-credential-issuer-1.0.0-rc.4/docs/technical-documentation/dev-process/How%20to%20contribute.md

**Comment by evegufy** [comment]
Hi @FaGru3n, it's referenced https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/CONTRIBUTING.md#how-to-contribute

**Comment by FaGru3n** [comment]
sorry for wrong mentioning i mean in general Readme

![image](https://github.com/eclipse-tractusx/ssi-credential-issuer/assets/121097161/a01061f3-654b-4f9a-a761-7cb36cfcbe42)

**Comment by evegufy** [comment]
done https://github.com/eclipse-tractusx/ssi-credential-issuer?tab=readme-ov-file#contributing
