### ISSUE TITLE
TRG 5.09 Upgradeability

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/ssi-credential-issuer#136]
Checked the point in our checklist, just a little reminder to enable helm upgrade step after release also stated here.

https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/fd8e687fa2ef80b2fef5b83206a7e4c206d7acf6/.github/workflows/chart-test.yml#L127-L130

**Comment by evegufy** [comment]
will be done once feature development for the next version starts
