### ISSUE TITLE
Validation of Table Schema for issuer.company_ssi_process_data - Potential Data Duplication with Document Table

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#188]
**Ticket Description:**

Identified a potential issue with the `issuer.company_ssi_process_data` table where the attribute named "schema" might be containing the entire credential, which could be a duplication of what is stored in the document table. This requires immediate attention to ensure data normalization and to prevent redundancy.

**Acceptance Criteria:**

1. Review the `issuer.company_ssi_process_data` table and confirm if the "schema" attribute contains the full credential.
2. Verify if the "schema" data is an exact duplicate of what is present in the document table.
3. If duplication is confirmed, assess the impact on the database performance and storage.
4. Determine if the "schema" attribute is necessary for the `issuer.company_ssi_process_data` table or if it can be referenced from the document table.
5. Propose a solution to eliminate redundancy without affecting the data integrity and the applications depending on this table.
6. Create a plan to clean up the duplicated data if it is deemed unnecessary.
7. Document any changes to the table structure and update any related data dictionaries or schema definitions.
8. Test the changes in a non-production environment before deploying to production.

**Steps to Reproduce:**

1. Query the `issuer.company_ssi_process_data` table to extract the contents of the "schema" attribute.
2. Compare the "schema" data with the corresponding entries in the document table.
3. Document any instances of duplication.

**Comment by Phil91** [comment]
@MaximilianHauer I checked the schema column. It is used to store the schema of the credential that should be created. That means we don't have duplicated data. Imo the issue can be closed
