### ISSUE TITLE
Environment value for Portal section is missing in helm chart for SsiCredentialIssuer.Expiry.App

### ISSUE THREAD

**Issue by dhiren-singh-007** [eclipse-tractusx/ssi-credential-issuer#195]
### Current Behavior
Getting error on running the SsiCredentialIssuer.Expiry.App for PortalSettings 
`...Exception":"Microsoft.Extensions.Options.OptionsValidationException: 
DataAnnotation validation failed for 'PortalSettings' members: 'BaseAddress' with the error: 'The BaseAddress field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'Username' with the error: 'The Username field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'Password' with the error: 'The Password field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'ClientId' with the error: 'The ClientId field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'GrantType' with the error: 'The GrantType field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'ClientSecret' with the error: 'The ClientSecret field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'Scope' with the error: 'The Scope field is required.'.; DataAnnotation validation failed for 'PortalSettings' members: 'TokenAddress' with the error: 'The TokenAddress field is required.'....`

### Expected Behavior
SsiCredentialIssuer.Expiry.App  should run successfully.

### Steps To Reproduce
1. Run the project `dotnet run` in SsiCredentialIssuer.Expiry.App using chart values.

**Comment by evegufy** [comment]
Hi @Phil91 even after the merge of https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/196, the cronjob appears to be missing configuration, see
[ssi-credential-issuer-rc-expiry-1.txt](https://github.com/user-attachments/files/16252877/ssi-credential-issuer-rc-expiry.1.txt)
I tested adding the following env var:

```
            - name: PROCESSIDENTITY__IDENTITYID
              value: ac1cf001-7fbc-1f2f-817f-bce058020006
```

but that leads to and the following error 
[ssi-credential-issuer-rc-expiry-2.txt](https://github.com/user-attachments/files/16253160/ssi-credential-issuer-rc-expiry.2.txt)

**Comment by jjeroch** [comment]
@dhiren-singh-007 please update the ticket status
