### ISSUE TITLE
Aggregate migrations since 1.0.0-rc.4.2

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/ssi-credential-issuer#199]
### Aggregate migrations

since 1.0.0-rc.4.2 to 1.1.0-rc.1

Required for https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/186

when?: after merge of https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/198

**Comment by ntruchsess** [comment]
it's mandatory to manually remove the preexisting entries that were created by the aggregated migrations from migration-history table:
```
DELETE FROM public.__efmigrations_history_issuer WHERE migration_id = '20240614180109_175-RenameMembershipCredential';
DELETE FROM public.__efmigrations_history_issuer WHERE migration_id = '20240618085801_118-AddTestCredential';
DELETE FROM public.__efmigrations_history_issuer WHERE migration_id = '20240711100008_190-AddDataExchangeGovernanceCredential';
INSERT INTO public.__efmigrations_history_issuer (migration_id, product_version) VALUES ('20240711100008_1.1.0-rc1', '8.0.5');
```
