### ISSUE TITLE
Document initial credential creation

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/ssi-credential-issuer#206]
### Current Behavior

The process through which the BPNL and Membership credentials are created for the initial/operator wallet by the SSI Credential Issuer is not documented.

### Expected Behavior

This process is documented.

### Steps To Reproduce

Detected in version 2.0.0

relates to https://github.com/eclipse-tractusx/portal-assets/issues/362

**Comment by jjeroch** [comment]
Reduced to high; understand why "highest" was proposed but this does not fit to the actual level definition of using highest for major incidents, full system outages, significant security issues, or substantial data loss
