### ISSUE TITLE
[E2E Test 24.08] Not possible to view documents when approving requests in Credential Request Overview menu

### ISSUE THREAD

**Issue by ds-hzimmer** [eclipse-tractusx/ssi-credential-issuer#225]
### Current Behavior

Logged in Portal as Company CX-Operator, in menu "Credential Request Overview" https://portal.example.net/admin-credential
it is possible to select the relevant request and approve (confirm) or deny it it. It is later also possible to revoke it.

![Credential Request Overview](https://github.com/user-attachments/assets/bbf396a9-3883-4c02-a041-ad0766a5e547)

However I was not able to open and validate the uploaded/linked file when clicking the icon or icons in the "Document" column for the respective request. Error message in a popup "Something went wrong. Please contact your administrator."

![Credential Request Overview - View Document - Something went wrong](https://github.com/user-attachments/assets/6a7e4ecf-768b-44c9-8caa-614a64e0d1b7)

This seems true regardless of the type of request or file type.

### Expected Behavior
When approving actual requests in a productive environment, the Operator should be able to review the supporting documents for a credential request.

### Steps To Reproduce
Trying to review any document in menu "Credential Request Overview" (pending, active, revoked, inactive).

Tested with deployed version for release 24.08 (2.1.0-RC2)

**Comment by evegufy** [comment]
Response:

```
{
    "type": "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.3",
    "title": "Access to requested resource is not permitted.",
    "status": 403,
    "errors": {
        "Org.Eclipse.TractusX.SsiCredentialIssuer.Service": [
            "Not allowed to access document of another company"
        ]
    },
    "errorId": "2e2217cd-d9d7-4cd0-811d-b114c61cab3d",
    "details": [
        {
            "errorCode": "DOCUMENT_OTHER_COMPANY",
            "type": "CredentialErrors",
            "message": "Not allowed to access document of another company",
            "parameters": []
        }
    ]
}
```
