### ISSUE TITLE
sig#781 - Adjust seeding data to support adding of initial credentials

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/ssi-credential-issuer#250]
### Description

The process through which the BPNL and Membership credentials for the initial/operator wallet is added to the Credential Issuer should be improved.
In the current state it requires direct interaction on database level to some extent: https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.1.0/docs/technical-documentation/operator-credential-creation/initial-credential-setup.md

### Acceptance Criteria

- [x] Seeding data is enhanced to support adding of initial credentials
- [x] No direct interaction on db level is needed anymore to import the initial/operator wallet

### Additional information

implements https://github.com/eclipse-tractusx/sig-release/issues/781

**Comment by Phil91** [comment]
@evegufy this issue is obsolete since I've adjusted the portal seeding in a way that the onboarding process will run for the operator company to create the wallet and the two credentials afterwards.

**Comment by evegufy** [comment]
Hi @Phil91 we'd still need to update the documentation, right? https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/v1.1.0/docs/technical-documentation/operator-credential-creation/initial-credential-setup.md
And wasn't there a 409 error due to issuer and holder being the same instance in the operator case, which we should take care of?

**Comment by MaximilianHauer** [comment]
`The portal will request a bpn credential via the endpoint POST: api/issuer/bpn which will create a process and a process step. **The process will currently fail at step 4 since the issuer wallet is the same as the holder wallet**. This will be fixed in the future. For now you can execute the following query to resolve the issue`

i assume we talk about this sentence ? would make sense to add the error code.

**Comment by Phil91** [comment]
@evegufy I adjust the documentation :)

Yes right, I add the handling for that in this PR as well. @MaximilianHauer this would make the error obsolete :)

**Comment by MaximilianHauer** [comment]
@Phil91 then i follow the finding of @evegufy  and propose a documentation update ;)

**Comment by MaximilianHauer** [comment]
@Phil91  should we move this into sprint 5 and adjust the status ?

**Comment by evegufy** [comment]
[docs](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/operator-credential-creation/initial-credential-setup.md) still needs to be updated

**Comment by Phil91** [comment]
> [docs](https://github.com/eclipse-tractusx/ssi-credential-issuer/blob/main/docs/technical-documentation/operator-credential-creation/initial-credential-setup.md) still needs to be updated

@evegufy added in #284
