### ISSUE TITLE
credential has wrong status after approval

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/ssi-credential-issuer#285]
### Current Behavior
When approving a framework credential it is directly set to active, even if it isn't existing in the wallet.

### Expected Behavior
The credential should only be active if it is existing in the wallet

### Steps To Reproduce
Create a credential, approve the credential with a not running process worker. The credential is set to active

**Comment by evegufy** [comment]
@Phil91 just wondering, did you forget to open a PR for https://github.com/eclipse-tractusx/ssi-credential-issuer/commit/9b90e2f01ad92f13edbe091f3f48e26c5c7e484e? :)

**Comment by Phil91** [comment]
> @Phil91 just wondering, did you forget to open a PR for [9b90e2f](https://github.com/eclipse-tractusx/ssi-credential-issuer/commit/9b90e2f01ad92f13edbe091f3f48e26c5c7e484e)? :)

I actually did - sorry, it's created now: https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/286

**Comment by evegufy** [comment]
we noticed that the change, should be accompanied by some usability improvements:
- https://github.com/eclipse-tractusx/portal-frontend/issues/1340
- https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/300
Will follow in the next release: 24.03
