### ISSUE TITLE
Credential Seeding Data Update 24.05. Scope

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-credential-issuer#45]
### Update the supported credentials for 24.05.

**Use Case:** `Circular_Economy`
**Credential:** `CircularEconomyCredential`
**ShortName:** CE
**Version:** 1.0
**Valid From:** to be discussed
**Template:** https://catena-x.net/fileadmin/user_upload/04_Einfuehren_und_umsetzen/Governance_Framework/231016_Catena-X_Use_Case_Framework_CircularEconomy.pdf

**Use Case:** `Demand_and_Capacity_Management`
**Credential:** `DemandCapacityCredential`
**ShortName:** DCM
**Version:** 1.0
**Valid From:** to be discussed
**Template:** https://catena-x.net/fileadmin/user_upload/04_Einfuehren_und_umsetzen/Governance_Framework/231016_Catena-X_Use_Case_Framework_DemanAndCapacity.pdf

**Use Case:** `Demand_and_Capacity_Management`
**Credential:** `PurisCredential`
**ShortName:** Puris
**Version:** 1.0
**Valid From:** to be discussed
**Template:** https://catena-x.net/fileadmin/user_upload/04_Einfuehren_und_umsetzen/Governance_Framework/231016_Catena-X_Use_Case_Framework_Puris.pdf

**Use Case:** `Business_Partner_Data_Management`
**Credential:** `BusinessPartnerCredential`
**ShortName:** BPDM
**Version:** 1.0
**Valid From:** to be discussed
**Template:** https://catena-x.net/fileadmin/user_upload/04_Einfuehren_und_umsetzen/Governance_Framework/231016_Catena-X_Use_Case_Framework_BPDM.pdf

### Remove credentials for 24.05.

- resiliency
- sustainability

**Comment by Phil91** [comment]
Included in #43

**Comment by jjeroch** [comment]
@Phil91  I miss circular economy on INT.
Covering the bug under https://github.com/eclipse-tractusx/ssi-credential-issuer/issues/95
